# Generated by Django 6.0 on 2026-01-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_blogpost_is_saved_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='current_agent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='current_task',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='progress_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
